spring.application.name=fishing-api
spring.profiles.default=dev
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/fishing_api}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:fishing}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:fishing}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul
spring.flyway.enabled=true

# LOGGING
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [%X{requestId}] %logger{20} | %msg%n

# Naver
naver.api.base-url=https://maps.apigw.ntruss.com
naver.api.key-id=${NAVER_API_KEY_ID}
naver.api.key=${NAVER_API_KEY}

# OpenWeatherMap
openweather.api.base-url=https://api.openweathermap.org
openweather.api.key=${OPENWEATHER_API_KEY}

# GPT
openai.base-url: https://api.openai.com/v1
openai.api-key: ${OPENAI_API_KEY}
openai.model: gpt-5.4

# OpenSearch
opensearch.base-url=${OPENSEARCH_BASE_URL:http://localhost:9200}
opensearch.index-name=${OPENSEARCH_INDEX_NAME:fishing_articles_v1}

# PHOTO_SIZE
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

# actuator endpoint
management.endpoints.web.exposure.include=health,info,prometheus
