CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    nickname VARCHAR(100) NOT NULL,
    profile_image_url TEXT,
    status VARCHAR(20) NOT NULL,
    role VARCHAR(20) NOT NULL,
    report_count INTEGER NOT NULL DEFAULT 0,
    last_login_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT uq_users_provider_user UNIQUE (provider, provider_user_id)
);

CREATE TABLE user_refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    refresh_token TEXT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    device_name VARCHAR(255),
    user_agent TEXT,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE community_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    region VARCHAR(50) NOT NULL,
    place_name VARCHAR(255),
    latitude DECIMAL(10, 7),
    longitude DECIMAL(10, 7),
    fished_at TIMESTAMP,
    fished_at_source VARCHAR(20),
    location_source VARCHAR(20),
    species VARCHAR(100),
    length_cm INTEGER,
    tackle_type VARCHAR(50),
    tackle_custom_text VARCHAR(255),
    thumbnail_image_url TEXT,
    like_count INTEGER NOT NULL DEFAULT 0,
    comment_count INTEGER NOT NULL DEFAULT 0,
    report_count INTEGER NOT NULL DEFAULT 0,
    visibility_status VARCHAR(20) NOT NULL,
    visibility_reason VARCHAR(30),
    hidden_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_posts_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE community_post_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    image_url TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    content_type VARCHAR(100),
    file_size BIGINT,
    width INTEGER,
    height INTEGER,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_post_images_post FOREIGN KEY (post_id) REFERENCES community_posts(id)
);

CREATE TABLE community_post_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_post_likes_post FOREIGN KEY (post_id) REFERENCES community_posts(id),
    CONSTRAINT fk_post_likes_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uq_post_likes_post_user UNIQUE (post_id, user_id)
);

CREATE TABLE community_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    parent_comment_id BIGINT,
    reply_to_user_id BIGINT,
    content TEXT NOT NULL,
    like_count INTEGER NOT NULL DEFAULT 0,
    report_count INTEGER NOT NULL DEFAULT 0,
    visibility_status VARCHAR(20) NOT NULL,
    visibility_reason VARCHAR(30),
    hidden_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES community_posts(id),
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_comments_parent FOREIGN KEY (parent_comment_id) REFERENCES community_comments(id),
    CONSTRAINT fk_comments_reply_user FOREIGN KEY (reply_to_user_id) REFERENCES users(id)
);

CREATE TABLE community_comment_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_comment_likes_comment FOREIGN KEY (comment_id) REFERENCES community_comments(id),
    CONSTRAINT fk_comment_likes_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uq_comment_likes_comment_user UNIQUE (comment_id, user_id)
);

CREATE TABLE community_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id BIGINT NOT NULL,
    target_type VARCHAR(20) NOT NULL,
    target_id BIGINT NOT NULL,
    reason_type VARCHAR(20) NOT NULL,
    reason_detail TEXT,
    status VARCHAR(20) NOT NULL,
    resolved_by BIGINT,
    resolved_at TIMESTAMP,
    admin_memo TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_user_id) REFERENCES users(id),
    CONSTRAINT fk_reports_resolved_by FOREIGN KEY (resolved_by) REFERENCES users(id),
    CONSTRAINT uq_reports_reporter_target UNIQUE (reporter_user_id, target_type, target_id)
);

CREATE TABLE user_sanctions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    sanction_type VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    reason TEXT NOT NULL,
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_sanctions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_sanctions_admin FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE INDEX idx_community_posts_created_at ON community_posts(created_at);
CREATE INDEX idx_community_posts_fished_at ON community_posts(fished_at);
CREATE INDEX idx_community_posts_region ON community_posts(region);
CREATE INDEX idx_community_posts_user_id ON community_posts(user_id);
CREATE INDEX idx_community_posts_map ON community_posts(fished_at, latitude, longitude);
CREATE INDEX idx_community_post_images_post_id_sort_order ON community_post_images(post_id, sort_order);
CREATE INDEX idx_community_comments_post_id_created_at ON community_comments(post_id, created_at);
CREATE INDEX idx_community_post_likes_user_id ON community_post_likes(user_id);
CREATE INDEX idx_community_reports_target ON community_reports(target_type, target_id);
CREATE INDEX idx_user_sanctions_user_id ON user_sanctions(user_id);
